{% set name = "Flask-Caching" %}
{% set version = "2.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 65d7fd1b4eebf810f844de7de6258254b3248296ee429bdcb3f741bcbf7b98c9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-cache-dir
  skip: True # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cachelib >=0.9.0
    - flask

# ModuleNotFoundError: No module named 'pylibmc'
{% set tests_to_skip = "test_init_nullcache" %}

test:
  source_files:
    - tests
  imports:
    - flask_caching
    - flask_caching.backends
  requires:
    - pip
    - pytest
    - asgiref
    - python-memcached
    - redis-py
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v -k "not {{ tests_to_skip }}" tests

about:
  home: https://github.com/pallets-eco/flask-caching
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Adds caching support to your Flask application
  description: A fork of the Flask-cache extension which adds easy cache support to Flask.
  doc_url: https://flask-caching.readthedocs.io
  dev_url: https://github.com/pallets-eco/flask-caching

extra:
  recipe-maintainers:
    - halldc