{% set name = "Flask-Caching" %}
{% set version = "2.4.0" %}
{% set tests_to_skip = "test_init_nullcache" %}
{% set tests_to_skip = tests_to_skip + " or test_set_make_cache_key_property" %}  # [win]

# ModuleNotFoundError: No module named 'pylibmc'
# AssertionError: assert '1749210855.961081' != '1749210855.961081'
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a7f14e43617cd0612a57bec2f80516d6d2ec888bfc50a807b1e4e41ca345a3b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-cache-dir
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - flit-core >=3.11,<4
  run:
    - python
    - cachelib >=0.9.0
    - flask >=2.0

test:
  source_files:
    - tests
  imports:
    - flask_caching
    - flask_caching.backends
  requires:
    - pip
    - pytest
    - asgiref
    - redis-py
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v -k "not({{ tests_to_skip }})" tests

about:
  home: https://github.com/pallets-eco/flask-caching
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Adds caching support to your Flask application
  description: A fork of the Flask-cache extension which adds easy cache support to Flask.
  doc_url: https://flask-caching.readthedocs.io
  dev_url: https://github.com/pallets-eco/flask-caching

extra:
  recipe-maintainers:
    - halldc
