travis:
  secure:
    BINSTAR_TOKEN: KmXf9iMZkUvTPs8YhENYUZ42MEnpvR8OxziZ9g3Fn+zmqTMaOYAjXb3ZirU7RmSOYNcahqKpjIoWooUbqWO/ieFuOYYrJ3fls8s4nNkH4SntcoDj0aNw1oDEoYEBgnh0mYOwrxhaUtYf8M5v1rXwPRf3Qw29gCDF3yI2OUP8CX4sm+wR6Bv9hHldYV9Wte++6kA/as+tPe0TsQp84gPvPZcLMEL6djFUnafGNDPmsqWXpVPP9rsWJuB1C3/eIifphf3ZcqqXy84AOxgRFheUBVrrnchv0GkIS2Vdw4YQlwI8L+HHIB6nhErYaARE4U7jTkv+SZTEdg7b6Zq6ONjeGiy9l7V0eSNK+/hOBRW2wnz/3t2Cm3JBWMdw3asvlQOreipLetBfKNJxhoyFM+6c05jStjiXSQC9Pe8mlzeXSz1TPgHyMwqFgaVQKnqsRfLW1rjquT0DlRiekhJavH6m9Ly+tcIUTNF8ZJaDfBSMOFcO/z3kUoV/LzY7NxLsAy+Q8L+AdX9QbE5u2i+cukq75+C6kkKgqgfDmMZtUDNyl12arW8uL+dFyO8DRePK8N9eLf4YrX1faQQiAr/T8aa3kswVm0tTsQvIMj0GjcomIWQDsW/lEVIONi5Ll/z0QNCSymt/MPsAWy71R2uendw4tkDjrcty3Yvr2Y7oIoYMp6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
